[package]
name = "crossterm"
version = "0.5.4"
authors = ["T. Post"]
description = "An crossplatform terminal library for manipulating terminals."
repository = "https://github.com/TimonPost/crossterm"
documentation = "https://docs.rs/crossterm/"
license = "MIT"
keywords = ["console", "color", "cursor", "input", "terminal"]
exclude = ["target", "Cargo.lock"]
readme = "README.md"

[features]
default = ["cursor", "style","terminal","screen","input"]

cursor = ["crossterm_cursor"]
style = ["crossterm_style"]
terminal = ["crossterm_terminal"]
screen = ["crossterm_screen"]
input = ["crossterm_input"]

[workspace]

members = [
    "examples/program_examples/snake",
    "examples/program_examples/first_depth_search",
    "crossterm_winapi",
    "crossterm_utils",
    "crossterm_cursor",
    "crossterm_style",
    "crossterm_terminal",
    "crossterm_input",
    "crossterm_screen",

]

[dependencies]
crossterm_screen =   { path = "./crossterm_screen", optional = true, version = "0.1.0" }
crossterm_cursor =   { path = "./crossterm_cursor", optional = true, version = "0.1.0" }
crossterm_terminal = { path = "./crossterm_terminal", optional = true, version = "0.1.0" }
crossterm_style =    { path = "./crossterm_style", optional = true, version = "0.1.0" }
crossterm_input =    { path = "./crossterm_input", optional = true, version = "0.1.0" }
crossterm_utils =    { path = "./crossterm_utils", version = "0.1.0" }

[lib]
name = "crossterm"
path = "src/lib.rs"

[[example]]
name = "logging"
path = "examples/program_examples/logging.rs"

[[example]]
name = "command_bar"
path = "examples/program_examples/command_bar.rs"

[[example]]
name = "try"
path = "examples/terminal.rs"